version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Required variables from .env
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      
      # Optional variables with defaults
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-true}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-chat-genius-rag}
      - MODEL_NAME=${MODEL_NAME:-gpt-4}
      - RAG_SERVICE_API_KEY=${RAG_SERVICE_API_KEY}
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 